#+TITLE: Internet Combinator Language Specification
#+AUTHOR: Hsin-Yi Chen (hychen)
#+OPTIONS: H:2 num:t toc:2
#+OPTIONS: ^:nil
#+OPTIONS: <:nil todo:nil *:t ^:{} @:t ::t |:t TeX:t

* Introduction

Internet Combinator Language, ICLang in short, is a cordination language for compositing things of internet.
and designed in dataflow mindset with [[en.wikipedia.org/wiki/Configurable_modularity][configurable modularity]].

Not like How we does when we building a application in conventional programming language, building a pplication 
in ICLang is totally different, and almost like like building a electronic circuit by wiring pins of integrated 
circuits.

Which means a developer defines applications as networks of "black box" processes, which exchange data across 
predefined connections by message passing, where the connections are specified externally to the processes. 

These black box processes can be reconnected endlessly to form different applications without having to be changed
internally. So, when a developer programs, he is doing visual thinking in his mind.

#+BEGIN_SRC ditaa
   +-----------------------------------------------+
   |      +-------------+     +--------------+     |
   |      |             |     |              |     |
str|[]--->[]in Read out[]---->[]in Print out[]--->[]status
   |      |             |     |              |     |
   |      +-------------+     +--------------+     |
   +-----------------------------------------------+      
#+END_SRC

This programming paradigm that uses a "data factory" metaphor for designing and building applications 
usually called [[https://en.wikipedia.org/wiki/Dataflow_programming][Data Flow Programming]], [[http://www.jpaulmorrison.com/fbp/][Flow-based Programming]].

This document defines the syntax for IClang programs and an informal abstract semantics for the meaning of such 
programs. We leave as implementation dependent the ways in which ICLang programs are to be manipulated, interpreted,
etc. 

The implementations should follow principle below:

- All components should be independent and stateless.
- All components should be able written in any conventional programming language.
- All connections between component ports should be parallelism.

** Program Structure

In this section, we describe the abstract syntactic and semantic structure of ICLang.

1. At the topmost level is IClang's lexcial structure. The lexical structure represents ICLang programs in 
   JSON files.
2. At the bottom level is a collection of components described in Chapter [[Components]].
  
* Lexical Structure

In this chapter, we describe the low-level lexical structure of ICLang.

** Lexical Program Structure

#+BEGIN_SRC javascript :tangle ../schema/hyperscript-schema.json
  {
      "$schema": "http://json-schema.org/schema#",
      "title": "ICLang HyperScript JSON Schema",
      "type": "object",
      "required":["properties", "processes", "connections"],
      "properties": {
          "comment": {"$ref":"#/definitions/comment"},
          "properties": {"$ref":"#/definitions/properties"},
          "processes": {"$ref":"#/definitions/processes"},
          "connections": {"$ref":"#/definitions/connections"},
          "inports": {"$ref":"#/definitions/inports"},
          "exports": {"$ref":"#/definitions/exports"}
      },
      "definitions":{        
          "properties":{
              "type":"object",
              "properties":{
                  "name":{
                      "type":"string",
                      "required": true
                  },
                  "description":{
                      "type":"string",
                      "required": true
                  }
              }
          },
          "processes":{
              "type":"object",
              "addtionalProperties":false,
              "patternProperties":{
                  "^[a-zA-Z]([a-zA-Z0-9]*?)":{
                      "type":"object",
                      "required":["component", "option"],
                      "properties":{
                          "component":{"type":"string"},
                          "option":{"type":"object"}
                      }
                  }
              }
          },
          "process_port":{
              "type":"object",
              "required":["process", "port"],
              "properties":{
                  "process":{"type":"string"},
                  "port":{"type":"string"}
              }
          },
          "connections":{
              "type":"array",
              "items":{
                  "type":"object",
                  "required": ["src", "dest"],
                  "properties":{
                      "src":{"$ref":"#/definitions/process_port"},
                      "dest":{"$ref":"#/definitions/process_port"}
                  }
              }
          },
          "inports":{
              "type":"array",
              "items":{
                  "type":"object",
                  "required":["name","dest"],
                  "properties":{
                      "name":{"type":"string"},
                      "dest":{"$ref":"#/definitions/process_port"}
                  }
              }
          },
          "exports":{
              "type":"array",
              "items":{
                  "required":["name", "src"],
                  "type":"object",
                  "properties":{
                      "name":{"type":"string"},
                      "src":{"$ref":"#/definitions/process_port"}
                  }
              }
          },
          "comment":{
              "type":"string"
          }        
      }
  }
#+END_SRC

As an example below, shows a IClang program.

#+BEGIN_SRC javascript :tangle ../example/simple-hyperscript.json
  {
      "properties":{
          "name":"read a string and print",
          "description": "read a string then print it to console."
      },
      "processes":{
          "Read":{
              "component":"ReadComponentId"
          },
          "Print":{
              "component":"PrintComponentId"
          }
      },
      "connections":[
          {
              "src":{
                  "process":"Read",
                  "port":"out"                
              },
              "dest":{
                  "process":"Print",
                  "port":"in"
              }
          }
      ],
      "inports":[
          {
              "name":"str",          
              "dest":{
                  "process":"Read",
                  "port":"in"
              }
          }
      ],
      "exports":[
          {
              "name":"status",
              "src":{
                  "process":"Print",
                  "port":"out"
              }
          }    
      ]
  }
#+END_SRC

*** Property: properties
TBD
*** Property: processes
TBD
*** Property: connections
TBD
*** Property: inports
TBD
*** Property: exports
TBD
*** Property: comments
    TBD
* Components

A component is a module of a conventional programming language, exports [[Component%20Definition][Component Definition]], a value declares component
metadata, such as name, description,etc. And [[Component%20Provider][Component Provider]] a function to provide the value. the name of the value 
and function should be corresponding to ones used in the ICLang runtime implemented in same conventional programming 
language.

In this chapter, we are using Node.JS implmentation of a component to explain the syntax and abstract meaning.

** Component Strucutre

Hre is the structure for Node.JS and components implemented in other conventional programming language 
should very simliary to this one.

#+BEGIN_SRC javascript
  module.exports.definition = {
      friendlyName: 'Do something',
      description: 'Do something with the provided inputs that results in one of the exit scenarios.',
      inputs: {
          apiKey: {
              description: 'The api key to be used.',
              example: 'foo',
          }
      },
      outputs:{
          out:{
              description: ''
              example: 'foo'
          }  
      },
    defaultExit: 'success',
      exits: {
          success: {
              example: 'myApiKey',
              description: 'Returns the API key for your totally fake account'
          },
          error: {
              description: 'Unexpected error occurred.'
          }
      },
      fn: function(inputs, exits) {
          // ...
          // your code here
      var result = 'foo';
          // ...
          // ...and when you're done:
          return exits.success(result);
      };
  }

  module.exports.provideComponent = function (options){
      return definition;
  }
#+END_SRC

As above shows, the Component Definition called *definition* and the Component Provider called *provideComponent*.

** Component Definition

Component Definition is a JSON that 

- is [[http://node-machine.org/spec/machine][Node Machine Specification]] compatible.
- can be verified by the following schema:

#+BEGIN_SRC javascript :tangle ../schema/component-schema.json
  {
      "$schema": "http://json-schema.org/schema#",
      "title": "ICLang Component Definition JSON Schema",
      "type": "object",
      "required": ["friendlyName", "fn"],
      "properties": {
          "friendlyName":{
              "type": "string"
          },
          "description":{
              "type": "string"
          },
          "inputs": {
              "type": "object"
          },
          "outputs":{
              "type": "object"
          },
          "defaultExists": {
              "type": "string"
          },
          "extis": {
              "type": "object"
          },
          "addtionalProperties":false,
          "patternProperties":{
              "^[a-zA-Z]([a-zA-Z0-9]*?)":{
                      "type":"object",
                      "required":["description"],
                      "properties":{
                          "description":{"type":"string"}
                      }
                  }
          },
          "fn": {}
      }
  }
#+END_SRC

*** Property: friendlyName
TBD
*** Property: description
*** Property: inputs
TBD
*** Property: outputs
TBD
*** Property: defaultExits
TBD
*** Property: exits
TBD
*** Property: fn

Component Function is a function recives two fixed arguments, inputs and exists

- inputs :: data recived on the ports of the component it belongs to after firing.
- exits :: callbacks.
           
** Component Provider

Component Provider is a function receives an fixed argument that the type is a object and returns [[Component%20Definition][Component Definition]].

* Evaluation

A IClang program is evaluated by ICLang interpreter. It instances procesess, connects ports betwen processes in order 
to indicate where data comes, how data be processed and where processed result goes.

** Processes
A process is an instance of a component.

- All process should have a UUID identifier.
- All process should be able to have zero to infinite InSocket or zero to infinite OutSocket.
- All process should starts firing if and only if the Firing Rules is satisfied.
  
** Sockets
A socket is an instance of a port which is place on a process to receiving or sending data.

- All sockets should have a UUID identifier.
- All socekts should be directional, the direction is either IN or Out, called InSocket or OutSocket.

** Connections
A logical link between a InPort and a OutPort  which allows one process is able to send data to another process.

- Each socket should not be connect to another socket of a process it belongs to.
- Sockets has same direction should be able to connect each other.

** Firing 
TBD

** Firing Rules
TBF
